CREATE DATABASE EventPlus;

CREATE TABLE TipoUsuario(
	idTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo VARCHAR(100) NOT NULL
);

CREATE TABLE TipoEvento(
 IdTipoEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
 Titulo VARCHAR(100) NOT NULL
);

CREATE TABLE Usuario(
 idUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
 Nome VARCHAR(100) NOT NULL,
 Email VARCHAR(256) UNIQUE NOT NULL,
 Senha VARCHAR(60) NOT NULL,
 IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario)
);

CREATE TABLE Instituicao(
 IdInstituicao UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
 NomeFantasia VARCHAR(100) NOT NULL,
 Endereco VARCHAR(100) NOT NULL,
 CNPJ VARCHAR(14) UNIQUE NOT NULL
);							

CREATE TABLE Evento(
 IdEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
 Nome VARCHAR(100) NOT NULL,
 DataEvento DATETIME NOT NULL,
 Descricao TEXT NOT NULL,
 IdTipoEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoEvento(idTipoEvento),
 IdInstituicao UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Instituicao(IdInstituicao)
);

CREATE TABLE Presenca(
 IdPresenca UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
 Situacao BIT NOT NULL,
 IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario),
 IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(IdEvento)
);

CREATE TABLE ComentarioEvento(
 IdComentarioEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
 Descricao TEXT NOT NULL,
 Exibe BIT NOT NULL,
 DataComentarioEvento DATETIME NOT NULL,
 IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario),
 IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(IdEvento)
 );