CREATE DATABASE Herois;
GO




CREATE TABLE Equipe(
IdEquipe UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Nome VARCHAR (100) NOT NULL,
Descricao VARCHAR(255) NOT NULL
);
GO


CREATE TABLE Heroi(
IdHeroi UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Nome VARCHAR (150) NOT NULL,
Poder VARCHAR (100) NOT NULL,
Idade INT NOT NULL,
IdEquipe UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Equipe(IdEquipe)

);
GO



CREATE TABLE Missao(
IdMissao UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Nome VARCHAR(100) NOT NULL,
Descricao VARCHAR(255) NOT NULL,
IdEquipe UNIQUEIDENTIFIER FOREIGN KEY REFERENCES  Equipe(IdEquipe),
IdHeroi UNIQUEIDENTIFIER FOREIGN KEY REFERENCES  Heroi(IdHeroi)
);
GO